# Generated by Django 4.2.29 on 2026-06-25 23:32

import apps.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_product'),
        ('inventory', '0004_alter_inventorylog_product_alter_stockalert_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('producer_type', models.CharField(choices=[('individual', 'Produtor Individual'), ('cooperative', 'Cooperativa'), ('company', 'Empresa Agrícola'), ('association', 'Associação')], default='individual', max_length=20, verbose_name='Tipo de produtor')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Nome da empresa / cooperativa')),
                ('nif', models.CharField(blank=True, help_text='Número de Identificação Fiscal (Portugal) - 9 dígitos', max_length=20, validators=[apps.products.models.validate_portuguese_nif], verbose_name='NIF')),
                ('bio', models.TextField(blank=True, verbose_name='Sobre o produtor')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='producers/logos/', verbose_name='Logótipo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='producers/banners/', verbose_name='Banner')),
                ('farm_name', models.CharField(blank=True, max_length=200, verbose_name='Nome da exploração')),
                ('farm_address', models.TextField(blank=True, verbose_name='Morada da exploração')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='Concelho')),
                ('parish', models.CharField(blank=True, max_length=100, verbose_name='Freguesia')),
                ('postal_code', models.CharField(blank=True, help_text='Ex: 3000-000', max_length=20, verbose_name='Código Postal')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telemóvel de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('bank_account', models.CharField(blank=True, help_text='Número de conta bancária (IBAN)', max_length=50, verbose_name='IBAN')),
                ('bank_owner', models.CharField(blank=True, max_length=200, verbose_name='Titular da conta')),
                ('status', models.CharField(choices=[('pending', 'Pendente de aprovação'), ('approved', 'Aprovado'), ('suspended', 'Suspenso'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rejeição')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejeitado em')),
                ('custom_commission', models.DecimalField(blank=True, decimal_places=2, help_text='Deixar vazio para usar a comissão padrão da plataforma', max_digits=5, null=True, verbose_name='Comissão personalizada (%)')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de vendas (€)')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total de encomendas')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Avaliação média')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total de avaliações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_producers', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_producers', to=settings.AUTH_USER_MODEL, verbose_name='Rejeitado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil de Produtor',
                'verbose_name_plural': 'Perfis de Produtores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='productapproval',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productapproval',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductApproval',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddIndex(
            model_name='producerprofile',
            index=models.Index(fields=['status'], name='products_pr_status_7b8035_idx'),
        ),
        migrations.AddIndex(
            model_name='producerprofile',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_d9e8dd_idx'),
        ),
    ]
