# Generated by Django 4.2.29 on 2026-06-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_product_image_remove_product_is_organic_and_more'),
        ('products', '0003_producerprofile_remove_productapproval_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProducerProfile',
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Perfil de Produtor',
                'verbose_name_plural': 'Perfis de Produtores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.producer',),
        ),
    ]
