# Generated by Django 4.2.29 on 2026-06-25 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_alter_store_options_remove_store_delivery_fee_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Referência')),
                ('delivery_name', models.CharField(max_length=200, verbose_name='Nome de entrega')),
                ('delivery_phone', models.CharField(max_length=20, verbose_name='Telemóvel de entrega')),
                ('delivery_street', models.CharField(max_length=300, verbose_name='Rua / Bairro')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('delivery_district', models.CharField(max_length=100, verbose_name='Distrito')),
                ('delivery_country', models.CharField(default='Portugal', max_length=100, verbose_name='País')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal (€)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Taxa de entrega (€)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Desconto (€)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (€)')),
                ('status', models.CharField(choices=[('pending', 'Pendente de pagamento'), ('confirmed', 'Confirmada'), ('processing', 'Em preparação'), ('shipped', 'Enviada'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Estado')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Notas do cliente')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas do administrador')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada em')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceite'), ('rejected', 'Recusada'), ('processing', 'Em preparação'), ('shipped', 'Enviada'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal (€)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Comissão (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão (€)')),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='A receber (€)')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de recusa')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to='orders.order', verbose_name='Encomenda')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_orders', to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Sub-Encomenda do Produtor',
                'verbose_name_plural': 'Sub-Encomendas dos Produtores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('product_unit', models.CharField(max_length=10, verbose_name='Unidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário (€)')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal (€)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Encomenda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='users.product', verbose_name='Produto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Item de Encomenda',
                'verbose_name_plural': 'Itens de Encomenda',
            },
        ),
    ]
