# Generated by Codex on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_privacy_policy_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_terms_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="marketing_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="marketing_opt_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="producer_public_profile_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

