# Generated by Codex on 2026-04-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producer",
                to="users.user",
                verbose_name="Utilizador",
            ),
        ),
    ]

