# Generated by Django 4.2.29 on 2026-06-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'A Processar'), ('paid', 'Pago'), ('failed', 'Falha'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('test_approved', 'Teste Aprovado')], default='pending', max_length=50)),
                ('payment_method', models.CharField(blank=True, choices=[('card_test', 'Cartão de Teste'), ('bank_transfer_test', 'Transferência Bancária Teste'), ('cash_on_delivery', 'Pagamento na Entrega'), ('mbay_test', 'MBay Teste'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('other', 'Outro')], max_length=50, verbose_name='Método de Pagamento')),
                ('is_test_payment', models.BooleanField(default=False, help_text='Marcar como True para modo desenvolvimento/teste', verbose_name='É Pagamento de Teste')),
                ('test_signature', models.CharField(blank=True, help_text='Exemplo: COVERDE-TEST para validação em modo teste', max_length=50, verbose_name='Assinatura de Teste')),
                ('test_password_hash', models.CharField(blank=True, help_text='Senha hasheada para validação (ex: 1234)', max_length=128, verbose_name='Hash da Senha Teste')),
                ('transaction_id', models.CharField(blank=True, help_text='Referência da transação do gateway', max_length=100, verbose_name='ID da Transação')),
                ('reference', models.CharField(blank=True, help_text='Referência gerada para rastreamento', max_length=100, verbose_name='Referência de Pagamento')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Tentativas de Pagamento')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
