# Generated by Django 4.2.29 on 2026-06-25 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_options_remove_store_delivery_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='test_password_hash',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='test_signature',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='payment',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Falhado em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Motivo de falha'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mb_way', 'MB WAY'), ('multibanco', 'Referência Multibanco'), ('paypal', 'PayPal'), ('card_test', 'Cartão Teste'), ('bank_transfer_test', 'Transferência Bancária Teste'), ('cash_on_delivery', 'Pagamento na Entrega')], default='card_test', max_length=30, verbose_name='Método de pagamento'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reembolsado em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='test_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado (teste) em'),
        ),
        migrations.AddField(
            model_name='payment',
            name='test_password_used',
            field=models.BooleanField(default=False, verbose_name='Senha de teste usada'),
        ),
        migrations.AddField(
            model_name='payment',
            name='test_signature_used',
            field=models.BooleanField(default=False, verbose_name='Assinatura de teste usada'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (€)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_test_payment',
            field=models.BooleanField(default=True, help_text='TRUE = pagamento simulado em modo de desenvolvimento. FALSE = pagamento real.', verbose_name='Pagamento de teste'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Encomenda'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Referência de pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em processamento'), ('paid', 'Pago'), ('failed', 'Falhado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('test_approved', 'Aprovado (Teste)')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ProducerPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor a pagar (€)')),
                ('commission_deducted', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comissão deduzida (€)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em processamento'), ('paid', 'Pago'), ('failed', 'Falhado')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_test', models.BooleanField(default=True, verbose_name='Payout de teste')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='orders.sellerorder', verbose_name='Sub-encomenda')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Pagamento ao Produtor',
                'verbose_name_plural': 'Pagamentos aos Produtores',
                'ordering': ['-created_at'],
            },
        ),
    ]
