# Generated by Django 4.2.29 on 2026-06-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='producers/verification/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
                'db_table': 'producers_producer',
            },
        ),
        migrations.CreateModel(
            name='ProducerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('organic', 'Organic (Bio)'), ('dop', 'DOP - Protected Designation'), ('pig', 'PGI - Protected Geographical Indication'), ('fair_trade', 'Fair Trade'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(upload_to='producers/certifications/')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='producers.producer')),
            ],
            options={
                'verbose_name': 'Producer Certification',
                'verbose_name_plural': 'Producer Certifications',
                'db_table': 'producers_producercertification',
            },
        ),
    ]
