# Generated by Codex on 2026-04-12

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


def clamp_existing_ratings(apps, schema_editor):
    Producer = apps.get_model("producers", "Producer")
    # Ajustar valores fora do intervalo para evitar problemas no Admin.
    Producer.objects.filter(rating__isnull=True).update(rating=1)
    Producer.objects.filter(rating__lt=1).update(rating=1)
    Producer.objects.filter(rating__gt=5).update(rating=5)


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=3,
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
        ),
        migrations.RunPython(clamp_existing_ratings, migrations.RunPython.noop),
    ]

