# Generated by Django 4.2.29 on 2026-06-27 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_product_image_remove_product_is_organic_and_more'),
        ('producers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producercertification',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Certificação do Produtor', 'verbose_name_plural': 'Certificações do Produtor'},
        ),
        migrations.AddField(
            model_name='producercertification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='producercertification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='producercertification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='producercertification',
            name='cert_type',
            field=models.CharField(choices=[('organic', 'Biológico'), ('dop', 'DOP - Denominação de Origem Protegida'), ('igp', 'IGP - Indicação Geográfica Protegida'), ('integrated', 'Produção Integrada'), ('fair_trade', 'Comércio Justo'), ('other', 'Outro')], max_length=50, verbose_name='Tipo de certificação'),
        ),
        migrations.AlterField(
            model_name='producercertification',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do certificado'),
        ),
        migrations.AlterField(
            model_name='producercertification',
            name='document',
            field=models.FileField(upload_to='producers/certifications/', verbose_name='Documento do certificado'),
        ),
        migrations.AlterField(
            model_name='producercertification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de validade'),
        ),
        migrations.AlterField(
            model_name='producercertification',
            name='issue_date',
            field=models.DateField(verbose_name='Data de emissão'),
        ),
        migrations.AlterField(
            model_name='producercertification',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome da certificação'),
        ),
        migrations.AlterField(
            model_name='producercertification',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users.producer', verbose_name='Produtor'),
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
