# Generated by Django 4.2.29 on 2026-06-25 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Classe FontAwesome, ex: fa-apple-alt', max_length=50, verbose_name='Ícone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='users.category', verbose_name='Categoria pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nome da empresa/quinta')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='suppliers/logos/', verbose_name='Logótipo')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telemóvel de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('address', models.TextField(blank=True, verbose_name='Morada')),
                ('status', models.CharField(choices=[('pending', 'Pendente de aprovação'), ('approved', 'Aprovado'), ('suspended', 'Suspenso'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil de Produtor',
                'verbose_name_plural': 'Perfis de Produtores',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('order_new', 'Nova encomenda'), ('order_confirmed', 'Encomenda confirmada'), ('payment_approved', 'Pagamento aprovado'), ('account_approved', 'Conta aprovada'), ('account_rejected', 'Conta rejeitada'), ('product_approved', 'Produto aprovado'), ('general', 'Geral')], default='general', max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], max_length=20, verbose_name='Género')),
                ('newsletter_subscribed', models.BooleanField(default=True, verbose_name='Subscrito a newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfis de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Casa'), ('work', 'Trabalho'), ('other', 'Outro')], default='home', max_length=20, verbose_name='Tipo')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('phone', models.CharField(max_length=20, verbose_name='Telemóvel')),
                ('street', models.CharField(max_length=300, verbose_name='Rua / Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('district', models.CharField(max_length=100, verbose_name='Distrito')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('country', models.CharField(default='Portugal', max_length=100, verbose_name='País')),
                ('is_default', models.BooleanField(default=False, verbose_name='Morada padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Morada',
                'verbose_name_plural': 'Moradas',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Token de Ativação',
                'verbose_name_plural': 'Tokens de Ativação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (€)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantidade em stock')),
                ('unit', models.CharField(default='kg', help_text='kg, unidade, litro, etc', max_length=50, verbose_name='Unidade')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem principal')),
                ('is_organic', models.BooleanField(default=False, verbose_name='Biológico')),
                ('certification', models.CharField(blank=True, help_text='Ex: DOP, IGP, Biológico certificado', max_length=200, verbose_name='Certificação')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('discontinued', 'Descontinuado')], default='active', max_length=20, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Em destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Avaliação média')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total de avaliações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.category', verbose_name='Categoria')),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Produtor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='users_produ_status_4fcfe3_idx'), models.Index(fields=['producer'], name='users_produ_produce_30430c_idx'), models.Index(fields=['category'], name='users_produ_categor_fdd57d_idx')],
            },
        ),
    ]
