# Generated by Django 4.2 on 2026-06-27 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_organic',
        ),
        migrations.AddField(
            model_name='product',
            name='extra_images',
            field=models.JSONField(blank=True, default=list, verbose_name='Imagens adicionais'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem principal'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Total vendido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='certification',
            field=models.CharField(blank=True, choices=[('', 'Sem certificação'), ('biologico', 'Biológico'), ('dop', 'DOP'), ('igp', 'IGP'), ('integrada', 'Produção Integrada'), ('tradicional', 'Produto Tradicional')], max_length=50, verbose_name='Certificação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Quilograma'), ('un', 'Unidade'), ('l', 'Litro'), ('pct', 'Pacote'), ('maco', 'Maço'), ('caixa', 'Caixa'), ('dúzia', 'Dúzia')], default='kg', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='users_product',
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome da quinta/empresa')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='producers/verification/', verbose_name='Documento de verificação')),
                ('status', models.CharField(choices=[('pending', 'Pendente de aprovação'), ('approved', 'Aprovado'), ('suspended', 'Suspenso'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da rejeição')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='Total de avaliações')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Total de produtos')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de vendas (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_producers', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
                'db_table': 'users_producer',
                'ordering': ['-rating', '-total_sales'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.producer', verbose_name='Produtor'),
        ),
    ]
