# Generated by Codex on 2026-04-11

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_cart_category_order_producer_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Email verificado em"),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="Usado em")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de verificação de email",
                "verbose_name_plural": "Tokens de verificação de email",
                "ordering": ["-created_at"],
            },
        ),
    ]

