# Generated by Codex on 2026-04-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA por email"),
        ),
        migrations.CreateModel(
            name="TwoFactorCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=128, verbose_name="Hash do código")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="Usado em")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código 2FA",
                "verbose_name_plural": "Códigos 2FA",
                "ordering": ["-created_at"],
            },
        ),
    ]

