# Generated by Codex on 2026-04-12

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_product_orderitem_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Apenas dígitos, com ou sem prefixo (ex.: 912345678 ou +351912345678).",
                max_length=15,
                validators=[
                    RegexValidator(
                        message="Número de telemóvel inválido. Use apenas dígitos, com ou sem prefixo (ex.: 912345678 ou +351912345678).",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="Telemóvel",
            ),
        ),
    ]

