# Generated by Django 4.2 on 2026-04-12 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Apenas dígitos, com ou sem prefixo (ex.: 912345678 ou +351912345678).', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Número de telemóvel inválido. Use apenas dígitos, com ou sem prefixo (ex.: 912345678 ou +351912345678).')], verbose_name='Telemóvel'),
        ),
    ]
