# Generated by Codex on 2026-04-12

from django.db import migrations


def set_superusers_to_admin(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(is_superuser=True).exclude(user_type="admin").update(user_type="admin")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_producer_user_protect"),
    ]

    operations = [
        migrations.RunPython(set_superusers_to_admin, migrations.RunPython.noop),
    ]

