# Generated by Django 4.2.29 on 2026-06-25 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_producerprofile_remove_productapproval_product_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='store',
            name='delivery_methods',
        ),
        migrations.RemoveField(
            model_name='store',
            name='operating_hours',
        ),
        migrations.RemoveField(
            model_name='store',
            name='total_reviews',
        ),
        migrations.AddField(
            model_name='store',
            name='accepts_returns',
            field=models.BooleanField(default=True, verbose_name='Aceita devoluções'),
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, verbose_name='Morada'),
        ),
        migrations.AddField(
            model_name='store',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em'),
        ),
        migrations.AddField(
            model_name='store',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stores', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por'),
        ),
        migrations.AddField(
            model_name='store',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Comissão da plataforma (%)'),
        ),
        migrations.AddField(
            model_name='store',
            name='county',
            field=models.CharField(blank=True, max_length=100, verbose_name='Concelho'),
        ),
        migrations.AddField(
            model_name='store',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_time_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Tempo de entrega estimado (dias)'),
        ),
        migrations.AddField(
            model_name='store',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Loja em destaque'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='store',
            name='parish',
            field=models.CharField(blank=True, max_length=100, verbose_name='Freguesia'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telemóvel'),
        ),
        migrations.AddField(
            model_name='store',
            name='return_policy',
            field=models.TextField(blank=True, verbose_name='Política de devoluções'),
        ),
        migrations.AddField(
            model_name='store',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de avaliações'),
        ),
        migrations.AddField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='store',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de encomendas'),
        ),
        migrations.AddField(
            model_name='store',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de produtos'),
        ),
        migrations.AddField(
            model_name='store',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de vendas (€)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='stores/banners/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='Logótipo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor mínimo de encomenda (€)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome da loja'),
        ),
        migrations.AlterField(
            model_name='store',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='products.producerprofile', verbose_name='Produtor'),
        ),
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Avaliação média'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente de aprovação'), ('active', 'Ativa'), ('suspended', 'Suspensa'), ('closed', 'Fechada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterModelTable(
            name='store',
            table=None,
        ),
    ]
